# https://taskfile.dev

version: '2'

vars:
  GREETING: Hello, World!

# test A
# test1
# test2
# ...
# test sute B
# test1
# test2
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test:sanity:
    desc: _
    cmds:
      - echo pytest -n 4 test_suite__sanity
      
  test:sute-a:
    desc: _
    cmds:
      - echo pytest -n 4 test_suite__sanity
  
  test:sute-b:
    desc: _
    cmds:
      - echo pytest -n 4 test_suite__sanity

  stage:multistage:
    desc: _
    # dependancies evaluation are in parllel
    deps:
      - task: test:sute-a
      - task: test:sute-b
    cmds:
      - echo postprosessing
      - echo "@@[task=stage:multistage][result=pass]"

  stage:multistage2:
    desc: _
    # dependancies evaluation are in parllel
    cmds:
      - task -p test:sute-atest:sute-b
      - echo postprosessing
      - echo "@@[task=stage:multistage][result=pass]"
